name: E2e testing

on:
  workflow_dispatch:
  push:
    branches: [ $default-branch ]
  push-request:
    branches: [ $default-branch ]

jobs: 
  cypress:
    defaults: 
      run:
        working-directory: src
    run-on: ubuntu-latest
    timeout-minute: 15

    steps:
    - uses: actions/checkout@v2
    - run: npm install
    - run: npm run build
      env: 
        NODE_ENV: production
      
    - name: Run project localy
      run: |
        npm install serve
        $(npm bin)/serve dist -s -p 8080 &

    - name: Run Tests
      uses: cypress-io/github-action@v2
      with:
        working-directory: src
        browser: chrome
        headless: true
      